### ISSUE TITLE
Calibration products for DC2 Run 1.1

### ISSUE THREAD

**Issue by SimonKrughoff** [LSSTDESC/DC2-production#111]
We need to call out the calibration products we need for the next data challenge.  We need multiple exposures of each time.  I'm suggesting 10 since for flats that gets to shot noise < 1% with single exposure illuminations of 10K electrons, but it would be good to get more if we can.

For flats, we will need sets for each band, but also may need to get sets for a variety of rotator angles since the spider imprints on the illumination pattern.

We most likely need:
- [ ] Several zero exposure length single snap visits to make master bias frames.
- [ ] Several 30 second single snap exposures simulated with the shutter closed for dark current correction (may not need these if the dark current is very low).
- [ ] Several 10K electron single snap exposures illuminated with a flat screen through the nominal filters for making the master flats for each band.
- [ ] Electronic layout of the amps (e.g. overscan locations, amp assembly orientations, nominal gain).
- [ ] Defect maps translated into DM readable defect maps.
- [ ] A set of high exposure flats for calculating the B/F correction.  I don't think this is band dependent, but maybe we should calculate the correction in each band anyway, just to make sure.
- [ ] We will need to either measure or be handed cross-talk coefficients for all the pairs where it matters.  See discussion in #66.

Most likely will not need (check when confirmed):
- [ ] Linearity maps (I think phosim is perfectly linear)
- [ ] PRNU correction (I think we are assuming a perfectly rectilinear grid, and people have shown the LSST sensors to only have 0.4% PRNU, so is sub-dominant anyway.  Check that phosim is treating it as such).

**Comment by cwwalter** [comment]
B/F will be turned on so that can be removed from the bottom section.

**Comment by SimonKrughoff** [comment]
OK, moved.

**Comment by johnrpeterson** [comment]
Simon, use:

pixelerror 0

if you don't want the PRNU.  it is rather small, as you say, so i'm not sure it would matter.  Also, PhoSim is linear by default.

**Comment by johnrpeterson** [comment]
Flats can be generated with the procedure defined at the end of here:

https://bitbucket.org/phosim/phosim_release/wiki/Walkthrough

You likely should not go brighter than ~5000 counts so a "domeint 18" would do
There are examples of this in examples/flats

There are three choices for levels of optimization:

Time on 8-core laptop for a bright flat:
A) quick :                                  50 minutes   
B) normal + backgamma=1 :    6.5 hours   
C) single photon:                      300 hours

Artifacts depending on level of approximation:
A) Quick:  Intentionally smooths over small-scale detector effects and some subtle (not visible w/o analysis) long range correlations that can be reduced by averaging over several sets) due to the optimization
B) Normal+backgamma=1:   some subtle (not visible w/o analysis) long range correlations that can be reduced by averaging over several sets)
C) Single photon:   none

The commands (for command file) are as follows:
A)  see examples/quickbackground
B)  backgamma 1.0
C)  backalpha 0.0000001
      backgamma 1.0

A, B, and C should all work fine for DM requirements (provided that "contaminationmode 0" is used, if not B & C are fine).  For very detailed work, like studying correlation patterns induced by BF then B or C should be used.

**Comment by cwwalter** [comment]
For master flats for correction for vignetting etc. We hope that a set of several exposures of averaged B) will give us a flat with the correlations removed.

After more discussion with John, Pierre and other experts we have determined for BF corrections options A) and B) above will not work. We either will need to use C) (perhaps with a smaller sensor) or find a new set of optimization parameters which will result in less residual correlation.

@salmanhabib, @adrianpope and all at ANL will work with @johnrpeterson and @PierreAstier to try to produce and characterize the variance of these flats so we can produce the products needed in the list made by @SimonKrughoff at the top of this issue.

We need the low exposure master flats as soon as possible for @heather999 and @nicolaschotard and the DM processing.  

For the high exposure DM correction kernel flats we are still discussing the technique with the DM and SAWG group (and this will be the content of the next-next SAWG meeting).

We will track the progress of the work at ANL in this issue.

**Comment by katrinheitmann** [comment]
Calibration products have been developed for Run 2.1i and are described in the main DC2 paper. Closing this issue now.
