### ISSUE TITLE
Is there a change in sprinkler/catsim necessary for Run 2.0?

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/DC2-production#138]
@jbkalmbach and I were discussing @TomGlanzman's #136 that Run 1.1 ran into ( IO errors on nersc due to simultaneous access of databases ). In particular the cause of the problem was due to accessing `/global/projecta/projectdirs/lsst/groups/SSim/DC2/agn_db_mbh_7.0_m_i_30.0.sqlite`, and this was being done multiple times for each instance catalog generation, once each time a chunk was accessed. The problem was solved with discussions between Tom, @jchiang87 and @danielsf  for Run 1.1 by having copies of the database which was ~ 200  MB. 
 

The question we were thinking about is whether this will be a problem for Run 2 when the sizes are much larger, and whether this needs a modification somewhere. Some of the things to worry about are:
-  [ ] How much larger with the database be in Run 2.0 ? (~ 100 times to ~ 20 GB) or is there currently an overdensity which will decrease substantially  
- [ ] If this cannot be handled, we cannot be handled we can talk about how to fix this (just noting that according to @jbkalmbach using the usual catsim mechanism with chunking produces this by default). 
- [ ] If this is fine for Run 2.0  we should forget about this till DC3 and keep it in a DC3 label

**Comment by katrinheitmann** [comment]
@rbiswas4 Has there been progress on this? Do we need to push this if we want to get Run 2.0 going at some point in April? Thanks!

**Comment by danielsf** [comment]
I am going to close this issue.  We have been able to generate ~ 1000 InstanceCatalogs in parallel with just the one AGN parameter database.

In order to generate more than a few 1000 InstanceCatalogs in parallel, it has proven necessary to make independent copies of the AGN database in Cori/Edison's SCRATCH space.  If we end up doing something like this from DC3, we should investigate a more efficient way of storing AGN parameters (i.e. hdf5 files or something similar).
