### ISSUE TITLE
Improve load speed of merged catalog HDF5 files

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-production#158]
#151  was limited to using HDF5 `fixed` format due to the large number of columns.  This limits load speeds and doesn't allow for conveniences such as loading only subsets of data and only having to due the I/O for those subsets.

1. [x] Measure performance impact
2. [x] If significant, then determine mitigations to improve load speed.

**Comment by wmwv** [comment]
The `table` format with HDF+PyTables has an effective limit on the number of columns -- the total header size is limited to 64kB.

pandas-dev/pandas#9590

**Comment by cwwalter** [comment]
@wmwv I've been going over your code to understand how you set it up. Sorry, I have been too slow!

But, at the same time I have been doing some research as to approaches to get around this issue. I'm just going to write some of them down here. I am not necessarily advocating any but I want to document them.

- Use the 'table' format but then persist each filter as a separate table.  Then, to use them together do a table join by using the pandas.merge or join.  We can have pandas automatically prepend a prefix on them. A nice extra step is that you could specify columns you want and then it would go make subset frames with each of those columns and join those.  Some information is in:

https://pandas.pydata.org/pandas-docs/stable/comparison_with_sql.html#join

Another thing to think about here is that this might have a more natural mapping on how we wind up doing things with qserve.

- This makes me a bit nervous since it it isn't really part of the core pandas. But the xarray project (https://xarray.pydata.org/en/stable/) which is used heavily by the geophysics community etc and was leveraged in that impressive demo that @SimonKrughoff showed us the other day could be used to construct a dataframe where we indexed each variable by it's filter.  So you could do something like:

base_SdssShape_xx['r'] or ['i'] etc.  

and can also do broadcasting and operations over the index.

- In terms of loading columns speed we could consider leveraging parquet instead of hdf5.  This is a designed to be column based format when you can load selected columns for performance. It is going to play a big role in pandas etc in the future and it will also be used in the project. See:

https://jira.lsstcorp.org/browse/RFC-465

for more info.  @brianv0 is a good contact person for learning about this.  Support already exists in pandas but you need to install ether pyarrow or fastparaquet to use it.

**Comment by cwwalter** [comment]
I also am interested in if the project has a plan as to how the multi band information will be presented in the DRP releases.  I think @rhl had a comment about this in a slack channel but I can't find it now.

**Comment by wmwv** [comment]
As explored in #190, using the `fixed` format didn't yield performance improvements.  But using just the 10% subset of columns actually needed in our present protoDPDD did make things much faster.

I'm going to leave this issue open to remind us that we should investigate the Parquet options once that's more widely used in Project (I'm hoping to get more up-to-date myself at the PCW next week).

**Comment by wmwv** [comment]
Closed by #269, #271, #274, #285 which create and start to investigate Parquet options.
