### ISSUE TITLE
PhoSim v3.7.14: performance and validation

### ISSUE THREAD

**Issue by TomGlanzman** [LSSTDESC/DC2-production#163]
This issue discusses performance and validation of a new PhoSim release, v3.7.14.  The motivation for this work is to recover the remaining ~10,000 long-running sensor-visits in Run 1.2p.  As background, the following is excerpted from Issue #65 the Run 1.2p operations log:

-----
Recent work by Adrian Pope and Tom Uram at Argonne motivated the release of phoSim v3.7.14, which has improved thread scaling. Recall that DC2 production -- so far -- has been limited to 8-threads in the raytrace step due to internal code inefficiencies when using more threads [ref work last Fall by Glenn and Tom]. As a performance and validation check, a single DC2 Run 1.2p visit has been run with the latest phoSim code. This note summarizes the tests.

The executive summary is that the code changes do, indeed, allow for efficient running of many threads, thereby enabling us to attempt recovering the ~10,000 remaining sensor-visits in DC2 Run 1.2p. There are some differences between the 8-thread (v3.7.9) and 54-thread (v3.7.14) images. Although these differences do seem not qualitatively significant, it would be good if others could take a more quantitative look.
[[Ref](https://github.com/LSSTDESC/DC2_Repo/issues/65#issuecomment-389323587)]

-----

Discussion of performance and validation are welcome here.

**Comment by TomGlanzman** [comment]
This discussion was started in issue #65.  To pick up the thread on performance, @adrianpope  says:
```
I'm not exactly sure how pthreads work with the compute node kernel, slurm, and affinity settings, but it
 is possible that pthreads are not "pinned" to a particular set of cores/HW-threads, and they may be
 allowed to migrate around the hardware resources. In this case, if there are fewer than 5 phosim
 instances running on a node, the pthreads from the remaining instances might be allowed to "spread
 out" and run a bit more quickly (though possibly less efficiently overall). I don't know as much about the
 runtime rules for pthreads on XC40/KNL as I do about OpenMP threads, so I'm trying to chat with Intel
 folks to learn more about how to control and measure this.

```
Indeed, pthreads are *not*, by default, pinned to specific cores or hw threads.  I did some work with 'taskset' last year after watching a node full of (multiple instances) x (multiple threads) using 'top'.  My observation is that threads seem to freely move about the node's cores, independent of how many instances are running.  By locking an instance of, say, 8-threads to a specific set of cores, there is a definite performance improvement.

-----

```
I'm also not exactly sure how the workflow works, but I had assumed that it tried to keep the same
 number of phosim instances active on a compute node until hitting the wall clock limit, eg. when one
 phosim instance on a node finishes, the workflow finds the next sensor visit from a task queue and
 launches it on the compute node, so very little time is spent with fewer than the expected number of
 phosim instances active.
```

Yes, when there are more jobs to process than available processing billets, the workflow will manage the resources and submit new jobs as old ones complete.  If there is a homogeneous set of jobs in the workflow, e.g., exclusively 8-thread raytrace jobs, then the workflow will, in effect, attempt to keep the same *number* of jobs running on each node at all times.  However, for an inhomogeneous workload, e.g., a mix of 8-thread raytrace + single thread 'trim' or bookkeeping steps, the workflow simply attempts to saturate the resources of that node (memory and cores) any way it can.  

For my v3.7.14 tests, there were 26 sensor-visits to process so five (5) nodes were requested in an attempt to complete the test ASAP.  No more than five instances of phoSim's raytrace ran on a single node at any given time but as instances completed, there were, in general, no new ones to fill the newly empty billet.  The entire processing period was about 12 hours in duration.

**Comment by cwwalter** [comment]
Hi All,

Do you have a sense how much of the improvement was due to explicit code changes you made and how much came from using the Intel compiler?  I'm wondering about how much using the compiler in other contexts would help.

**Comment by adrianpope** [comment]
I think the entirety of the improvement in the thread-scaling of raytrace is due to source code changes. The Intel compiler seems to speed up the single-threaded start up region in raytrace by a noticeable amount on KNL, but the performance differences between GNU and Intel compilers in the threaded region seems to be pretty small for v3.7.14 on KNL.

I don't think it's easy to predict which compiler will do what for an arbitrary code on different architectures, so my advice would be to compile with both and run some semi-realistic performance comparisons if possible.

Part of my bias toward Intel compilers in this particular context is that I'm trying to profile the code with Intel Vtune, and this is somewhat easier to do with Intel compilers, though it is certainly also possible to do this with GNU compilers.

**Comment by TomGlanzman** [comment]
@cwwalter here is a plot from last September (using a beta version of phoSim on a Haswell node) that shows the curious behavior of gcc vs. Intel for various numbers of threads:

![image](https://user-images.githubusercontent.com/9436484/40145009-2b85aa1a-5915-11e8-8f17-968ce887ff94.png)

And if 'taskset' is added in (processor affinity), the change becomes more interesting:

![image](https://user-images.githubusercontent.com/9436484/40145088-68f9de02-5915-11e8-9f3b-62dc0966658e.png)

Of course, these plots will have changed with 3.7.14.

**Comment by heather999** [comment]
Hi, 
Tom asked if I could run the same visit which was simulated using both v3.7.9 and v3.7.14 through what we sometimes call the mini-DRP, which involves ingesting and running processEimage followed by makeFpSummary.  I've done that using the same reference catalog: `/global/projecta/projectdirs/lsst/groups/SSim/DC2/reference_catalogs/dc2_reference_catalog_dc2v3_fov4.txt`
and the w_2018_14 version of the stack plus the LSSSTDESC copy of obs_lsstSim. 
The resulting files are all available for v3.7.9:
`/global/cscratch1/sd/desc/DC2/w_2018_14/test-phosim/output-v3.7.9`
and v3.7.14:
`/global/cscratch1/sd/desc/DC2/w_2018_14/test-phosim/output-v3.7.14`
Log files can be found in `/global/cscratch1/sd/desc/DC2/w_2018_14`. It may be useful for experts to take a look at the processEimage and makeFpSummary outputs.
A quick visual can be found by looking at the png files produced by makeFpSummary
![v12449-fy-focalplane-summary-v3 7 9](https://user-images.githubusercontent.com/10982136/40259940-4e9c2f30-5ac6-11e8-8377-4933652119fe.png)
![v12449-fy-focalplane-summary-v3 7 14](https://user-images.githubusercontent.com/10982136/40260023-9a374ea2-5ac6-11e8-8627-6f2d224a2129.png)

**Comment by fjaviersanchez** [comment]
Some plots comparing the outputs from 3.7.9 and 3.7.14:

The background on 3.7.14 is 25% lower than in 3.7.9, in the plot below I am representing 3.7.9_pixel_value/3.7.14_pixel_value-1:

<img width="603" alt="screen shot 2018-05-16 at 2 00 13 pm" src="https://user-images.githubusercontent.com/13971732/40292524-acf052c6-5c80-11e8-9428-9f38da0ca364.png">

The overall distribution of magnitude looks a little bit fainter on 3.7.14 but I think that might be because of the difference in the background level:

![image](https://user-images.githubusercontent.com/13971732/40292558-e5008118-5c80-11e8-87f6-3b5479be3944.png)

Then I made spatial matching of the objects' centroids and the astrometry looks compatible:

![image](https://user-images.githubusercontent.com/13971732/40292592-0debbd54-5c81-11e8-98f9-7f84778250e6.png)

![image](https://user-images.githubusercontent.com/13971732/40292605-16de1b96-5c81-11e8-809f-d6642c990e8d.png)

Finally, I checked the measured magnitude difference (mag_3.7.9-mag_3.7.14) as a function of the magnitude measured in 3.7.9 and this is what I get:

![image](https://user-images.githubusercontent.com/13971732/40292669-6880faae-5c81-11e8-8e0f-a933f441a588.png)

The error-bars are the standard deviation of the difference divided by the square root of the number of entries in that bin. And below is the histogram of the difference:

![image](https://user-images.githubusercontent.com/13971732/40292703-976c8dce-5c81-11e8-87b0-1c0d89c8dd02.png)

**Comment by fjaviersanchez** [comment]
@sethdigel are the images with the diagonal structure the corresponding to the sensors close to the edge of the focal plane/is the order on your 4x4 grid from left-right/top-bottom the same as the list of paths that you include in your post? I'll re-check the ratio.

**Comment by cwwalter** [comment]
@fjaviersanchez Are you comparing full focal planes?  Do to the vignetting, if you were comparing something mostly on the outside of the focal plane to something mostly inside I think you would see an overall difference.  Or is this a apples-to-apples sensor by sensor comparison?

**Comment by fjaviersanchez** [comment]
so for the first histogram I was using the ratio between R30_S20 in 3.7.9 and 3.7.14. I don't know how I read 25%, I was still jet-lagged I guess... I am finding 6% consistent with @sethdigel's findings.

For the magnitude histogram I take the full datasets so it's not completely apples to apples because there are more visits processed for one dataset than the other but, the overall trend looks like 3.7.14 allows to detect slightly fainter objects (expected because the background is lower). For the rest I match the two source catalogs and I only use objects that have been matched to something closer than 0.5 arcseconds so, it should very close to apples-to-apples.

**Comment by johnrpeterson** [comment]
so just to be clear, the changes from v3.7.9 to v3.7.14 affected the random number generation.  this has more of an effect than you might expect, because everything including global things like the sky background level would be different (not just details for individual photons).  so you should expect different patterns & levels for almost anything in phosim.  the only thing to worry about is new unexpected results that didn't occur before, so as far as i can tell everything is ok.

**Comment by sethdigel** [comment]
> are the images with the diagonal structure the corresponding to the sensors close to the edge of the focal plane/is the order on your 4x4 grid from left-right/top-bottom the same as the list of paths that you include in your post? I'll re-check the ratio.

Yes, the order in the 4x4 grid left-right/top-bottom is the same as in the list with the ratios.  No, they do not seem to be the edge-most sensors.  I was too lazy to lay them out like the focal plane images above.  I may be able to try it tonight if it is worthwhile.  I was mostly interested to see the shapes of the ratios.

**Comment by fjaviersanchez** [comment]
@sethdigel, in my opinion it is not necessary to lay them on the correct positions on the focal plane, any other thoughts on this @cwwalter?
