### ISSUE TITLE
Review of color-color locus tutorial

### ISSUE THREAD

**Issue by patricialarsen** [LSSTDESC/DC2-production#207]
Review comments for tutorial notebook: 
DC2 Coadd Run1.1p direct access -- color-color stellar locus
(@wmwv)

**Comment by patricialarsen** [comment]
@wmwv 

I can get the notebook to run properly and it looks good overall - it's clear to me how to read in the catalog and do color-color locus plots of this. 

Minor points:
- It would be useful to have a brief explanation of what the "tract-patch catalog" is.
- I'm not very clear on how "extendedness" is defined, is this cut at 1 a standard way of dividing between galaxies and stars?
- The later plots could do with a brief title or description. In particular the scatter plot with two populations isn't very clear- what are the two populations here?

The density estimation section of this doesn't work, is a known issue from the comments:
- if you change the pandas arrays into numpy arrays, just by doing x = np.array(x) and y = np.array(y) you fix the issue you currently have. But I do still get a conflict after doing that:
"`bw_method` should be 'scott', 'silverman', a scalar or a callable. "
If I try to set bw_method to one of these in the input to gaussian_kde it says that __init__() got multiple values for argument 'bw_method'

**Comment by patricialarsen** [comment]
By the way, as a follow on from the first point, there's a nice explanation in the Plotting_the_Run1.1p_skymap notebook about what the geometry is.

**Comment by sschmidt23** [comment]
I was also assigned this notebook, so I'll comment here rather than a new issue.  

Overall, I think this needs some more comments to flesh out what exactly is being done.  Mention what the merged_tract_data_dir, that we are going to look at one single patch, and if there's a reason why we chose the particular patch (is it in the middle?) state why it was chosen.

For the first scatter plot of colors, state that first we're going to plot with no cuts, so this includes very low S/N objects and we expect it to look messy.  

The documentation says that we are just drawing two lines, but it looks like you're plotting a curve from a table, that should be clarified.  For the Davenport stellar locus model, state where the table comes from (is it referenced in the Ivezic paper that is already cited, or was this updated and that reference needs to be updated?).  Are the colors in the table specific to the LSST filters?  If they are for SDSS, DES, or some other filters, does that explain the slight offset in the bright star 2D histogram between the density contours and the red dashed line?  If so, state that in comments

I would paste the image from the 
http://www.astroml.org/examples/datasets/plot_sdss_imaging.html
directly into the notebook for comparison, or at least more explicitly state that we are going to make plots to compare to it.  The current "see e.g."  didn't really convey that the link had plots to directly compare.

As mentioned above, the last cell with density contours is broken.  I don't have time to try to get it working, though I'll note that seaboard has a very nice looking kde plotting function that I think looks much better than the scipy one, see a simple example here:
https://github.com/sschmidt23/Scratch/blob/master/seaborn_kde_example.ipynb

Minor comment:
The labels on the plots are tiny on my little laptop screen, I might add an
plt.rcParams['axes.labelsize'] = 18 
or something similar

**Comment by katrinheitmann** [comment]
@wmwv Can you address the comments or if they have been already addressed, close this issue? Thanks!

**Comment by wmwv** [comment]
This was moved to https://github.com/LSSTDESC/DC2-analysis/blob/master/tutorials/object_pandas_stellar_locus.ipynb
in the move of Notebooks from DC2-production to DC2-analysis.
