### ISSUE TITLE
Planning out GCR interface for transient objects

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/DC2-production#236]
@yymao @rbiswas4 @jchiang87 @djperrefort @DominiqueFouchez 

We had a Hack Day conversation about how to access transient objects using GCR and focused on the backend of the truth objects and the DM output. 

Here is my summary of what I understood to be the results of the discussion. Please comment on things I might have misunderstood or not elaborated enough upon.

### Truth

Since the instance catalogs are done for every visit and the transient sources will have entries in the instance catalogs for each visit we can use the instance catalogs as our input to a database to hold the information for the objects.

This user-facing API will draw from the "truth database" system which will have one table with the static properties and the `object_id`. The `object_id` can be matched against a separate table that will hold transient information which at least will be the `visit`, `mjd`, `flux`, `flux_err` properties for each visit in which the object appears.

### DM-Catalog Output

The `DIA Object` table will have the static information for all potentially transient objects while cutting out the majority of static objects allowing us to search a smaller dataset when looking for light curves. The transient information for these objects will be found in the `forced_photometry` tables that are created after the population of the `DIA Object` table.

The GCR interface will interact with these tables when the user asks for light curves.

## Additional Properties

Additional properties such as `max SNR` will be served to the user from Add-On catalogs as expected by the GCR interface already.

**Comment by danielsf** [comment]
---
Since the instance catalogs are done for every visit and the transient sources will have entries in the instance catalogs for each visit we can use the instance catalogs as our input to a database to hold the information for the objects.
---

This sounds to me like we are planning to generate the InstanceCatalogs and then scrape them for transient information to go into the truth catalog.  I do not think that is necessary.  It is fairly straightforward to

1) collect all of the variability parameters for all of the variables and transients in DC2

2) spatially crossmatch those sources against the DC2 visits to see when each source will actually be observed*

3) generate `flux` and `flux_err` for each source only at the times it is in the telescope's field of view in a vectorized way

This should be faster than putting an afterburner in that reads in the InstanceCatalogs and generates the truth table from them.  It will also allow us to use the truth catalog to validate the InstanceCatalogs, since it will have been generated before the InstanceCatalogs were written (in CosmoSims, we talked about using the truth catalog to validate that the InstanceCatalogs were correct before they get shipped off to image simulation).

* One concern about step 2 is: do we care whether or not the truth table reflects chip gaps or the non-circular nature of the LSST field of view (i.e. if an object is within our 2-degree field of view but not actually on a detector for a given visit, do we mind if still has an entry in the truth catalog)?  It is, of course, possible to only retain those objects that are actually on a detector but

a) the process will be slower
b) there is not 100% agreement between the CatSim prediction for "this object was on a detector" and PhoSim actually simulating the object on a detector

These are my thoughts.  I have implemented about 80% of this scheme in the u/danielsf/truth/catalogs branch on sims_GCRCatSimInterface (which may explain why I am advocating for it).  See, specifically the `write_sprinkled_lc` method in this file

https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/u/danielsf/truth/catalogs/python/desc/sims/GCRCatSimInterface/TruthCatalogLC.py

I am going to be camping until August 6 so I won't be terribly responsive until then.

**Comment by katrinheitmann** [comment]
@danielsf @jbkalmbach @yymao Hi all, was this actually finished and is documented somewhere? Thanks!

**Comment by yymao** [comment]
For the "truth" part, yes, and Scott has created the truth catalog and I have implemented the GCR interface (very similar to what's described here) with [a tutorial](https://github.com/LSSTDESC/DC2-analysis/blob/master/tutorials/truth_gcr_variables.ipynb) demonstrating the usage.

We don't have DIA object table yet. 

We have not generated additional properties (e.g., max SNR) nor developed the corresponding add-on interface. 

That said, it seems appropriate to close this issue (and open a new one when we have DIA object table and/or summary statistics as additional properties).
