### ISSUE TITLE
Run 2.0i WDF image simulation resource requirements (storage and compute time)

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2-production#253]
This issue summarizes the requirements for storage and compute time for the Run 2.0i image simulation campaign focusing on WFD. The storage requirement estimate is based on results from Run 1.2i. 

**Storage estimate:**

| Run | # of visits | # of sensor visits | instance catalog | image catalog | 
|----|----|----|----|----|
| 1.2i    | 2001  | ~159,000 | ~700GB | ~9TB | 
| 2.0i   | ~50k = 27k full | ~5M (27k*189) | ~23TB | ~300TB|

The number of visits for Run 2.0 is taken from [https://docs.google.com/presentation/d/1LaRajPigWE3hv6oyXxl9klpSmFp9GlfhbtYgveM17cs/edit#slide=id.g3db53f9830_1_161] and is taking into account that most visits are only partial visits (that leads to the reduction to 27k full visits). 

**Allocation estimate on Theta:**

One sensor visit takes ~12 hours on Theta (which is equal 12 Theta hours) and we can run 64 per node. This translates to an allocation requirement of ~60M Theta hours, which would be our FY18 allocation on Theta.

If the storage requirements look more or less correct, I can request an increase of our storage accordingly. This will only be temporarily available though. @cwwalter, @jchiang87, @heather999 please take a look. Thanks!

**Comment by cwwalter** [comment]
One note: I think there is a SED directory in the instance files that imSim doesn't use but PhoSim needs since we are using the stack supplied ones.  I think these don't need be staged to Theta.  @jchiang87 or @danielsf can confirm if I am remembering this correctly.  That can save some space. It's not a factor of two but it isn't completely negligible as I recall. So, if the input files need to go on a smaller volume it might help.

**Comment by katrinheitmann** [comment]
Thanks @cwwalter! Reduction is always good!

Maybe @jchiang87 can clarify -- I based the instance catalog number on 
what is currently there for Run 1.2i on Theta. Is that more than needed 
following Chris' argument?

**Comment by jchiang87** [comment]
Just to be clear, in each instance catalog directory for Run1.2p, there is a subfolder called `Dynamic` that contains SED files that are used by the sprinkled objects for that visit, so those files need to be retained.  For running phosim at NERSC, there may be separate staging of the more general SED files that come with the Stack, but they are not in the instance catalog folders that were copied to ANL.  So I think the current number in the table for the Run1.2i instance catalogs is correct as-is.

**Comment by cwwalter** [comment]
Yes, I was referring to the static SED directory in the directories at NERSC.

```
/global/cscratch1/sd/descpho/Pipeline-tasks/DC2-R1-2p-WFD-r/000006
cori03:000006 % ls
SEDs/  commands.txt  instCat/  output/
```

But, it sounds from Jim like those were already not copied to Theta.

**Comment by humnaawan** [comment]
Here's a summary of some estimates for the number of sensors to be simulated, based on the visit lists I've produced for Run 1-2:

|    Run/Survey   | Nside | nobsIDs  | nobsIDs (chip-count code) | nChips (science sensors) | | Time taken on login node (hrs)
|:---------:|:-----:|:-----:|:--------:|:------:|:------:|:------:|
| Run 1 DD  |  512  | 23,160 |   23,160 | 888,758 | | 16.20
| Run 2 DD  |  256  | 23,160 |   23,160 | 855,299 | | 4.65
| Run 2 DD  |  1024  | 23,160 |   23,160 | 846,139 | | 50.69
| --- | --- | ---  | --- | --- |  | --- | 
| Run 1 WFD |  512  | 8,389  |   8,374   | 616,072 | | 10.75
| Run 2 WFD |  512  | 51,122  |   51,063 | 5,612,971 | | 31.19
|||||| ||
|||||| ||
| Run 2 WFD |  1024  | 50,415  | ?? | ?? | | ?

I don't have the number of sensors for Run 2 WFD at Nside 1024 since my code was taking very long to finish. Please see this [Issue](https://github.com/LSSTDESC/DC2_visitList/issues/2) in the DC2_visitList repo for the code and more details. 

However, based on the numbers so far, the chip count for DD goes down between Nside 256 and Nside 1024, so if we assume a similar trend for WFD, we'll be in the range of 5M sensors for all WFD Run 2 visits -- comparable to that from 27K full visits, which translate to ~27k x 181= 4,887,000 science sensors (181, not 189 since 8 wavefront sensors are not simulated).

**Comment by katrinheitmann** [comment]
**Conclusion:** The storage requirements listed at the top seem plausible. The computing requirements were based on Run 1.2i and therefore too low. As discussed in some detail here: https://docs.google.com/document/d/1QPhg3ANg51ymzx-pNAjGBxfxCybX_UUwQUZiizRi6Ls/edit#heading=h.8u8aeivssvj4, the Run 2.x catalogs require more imsim resources. However, after the google doc was completed, several major improvements were made to imsim so that the results in the document are upper limit estimates rather than accurate estimates. With the current version of imSim running on Cori, we can carry out ~45k visits for 2M hours, so 5M visits for WFD would require ~220M (the original estimate in the google doc was closer to 300M hours). Since the charges on Cori are reduced at our 2000 node job size, we would be charged 176M Cori hours. The charges on Theta are lower by a factor of ~3 (more memory allows more imsim jobs per node and different charging model, 1 node hour on Theta = 1.5 node hours on Cori ) so 10 years of WFD would be more like 70M hours. Currently, the plan is to run the first ~5 years on Cori and then reevaluate. I am closing this issue for now.
