### ISSUE TITLE
preliminary phosim performance on 2.0i inputs

### ISSUE THREAD

**Issue by adrianpope** [LSSTDESC/DC2-production#279]
Phosim: v3.7.16, source/raytrace/main.cpp augmented with timing information, compiled with Intel 2018 (no AVX512 instructions, but that hasn't made much difference in the past).

Architecture: 64-core KNL 7210 in JLSE at Argonne, should be within ~20-30% of the performance of ALCF/Theta (64-core KNL 7230) or NERSC/Cori (68-core KNL 7250).

Inputs: 2.0i, u-band, visit 3033, sensor R22_S11
Included: stars, bulges, disks (~500k sources total)
Excluded: bright_stars, agn, knots
Commands: 1.2p ("optimized" background, source_per_thread=100)

Issues: source/raytrace/parameters.h originally had MAX_SOURCE set to 150k, which caused a segmentation fault while parsing in raytrace, so I recompiled with MAX_SOURCE set to 1.5M and it worked. It may be ok to set MAX_SOURCE quite high if it is all allocated off the heap, since the virtual memory footprint might go up, but only memory that gets used should contribute to the physical memory footprint. Further testing required to verify, eg. is any memory manually filled with zeros out to MAX_SOURCE?

Timing with 256 pthreads:
Total: 68.9 min
Raytrace: 38.5 min
SourceLoop (threaded): 22.5 min
SourceLoop: 96.1 thread-hours occupied, 21.9 hours CPU, 22.8% parallel efficiency

Derived timings for single-threaded regions:
Before raytrace: 30.4 min
During raytrace: 16 min (5 min in parser)

I want to approximately compare to 1.2p production configurations, which used 8 threads for v3.7.9 and 54 threads for v3.7.15. I took the total CPU time from SourceLoop and assumed 90% parallel efficiency, which seems achievable from past experience.

8 threads:
SourceLoop (90%): 183 min (3:03)
Raytrace: 199 min (3:19)
Total: 229 min (3:49)

54 threads:
SourceLoop (90%): 27 min
Raytrace: 43 min
Total: 73 min (1:13)

The output e-image looks reasonable. The estimated production timings look relatively low, but this is a u-band sensor-visit with ~100 e-/pixel in the background and few brighter sources, so it should be on the very quick end of timing distribution. Also, phosim timings seem roughly proportional to total number of photons (though source and background photons are not quite equally weighted) modulo load-balancing, and I think 2.0 is mostly adding fainter objects compared to 1.2, so I would expect timings to be similar with the same physics settings.

Top level directory at NERSC:
/global/projecta/projectdirs/lsst/groups/CI/apope/JLSE/phosim_2.0i

Sub-directory with KNL outputs:
/global/projecta/projectdirs/lsst/groups/CI/apope/JLSE/phosim_2.0i/Run2.0i/JLSE/57051

**Comment by cwwalter** [comment]
> Commands: 1.2p ("optimized" background, source_per_thread=100)

I think by "optimized" here you mean the default parameters.

According to our work in 

https://github.com/LSSTDESC/DC2-production/issues/267#issuecomment-422397802

"backgamma 1"

may need to be set to reduce the correlation of the sky background. This decreases the optimization.  Understanding the amount of correlation which is problematic for B/F (which is how we noticed the effect) versus things like correlated noise after sky subtraction (if B/F was not required in 2.0p) would need further study or thought.

**Comment by adrianpope** [comment]
Re: backgamma, this test was meant as a very rough check of whether there were significant phosim slow-downs using ~DC2 catalogs with more faint objects, so we wanted to keep settings the same as 1.2p. This test was not meant to be used as a way to estimate 2.0/2.1 resource usage, which would require running the setting that we would intend to use, eg. a different backgamma. We would also probably want to use multiple/different bands, as u-band is not very representative of typical phosim run time due to low background.

**Comment by adrianpope** [comment]
Also, after the original post I realized that my estimates for 8-thread and 54-thread timings are overly optimistic due to power/clock-frequency effects. I ran a single phosim instance on a KNL node, so not load balanced. When there are only a few threads left running the bright objects, the active cores can use more power and increase the clock frequency more than if the node is loaded. I don't know the magnitude of this effect, but I expect it to be <2x from previous experiments. Anyway, the CPU time estimates for sourceLoop are going to be a bit low because of this, so the 8-thread and 54-thread projects for sourceLoop should be a bit higher. But, again, this test was not meant to be used for performance projection.

**Comment by katrinheitmann** [comment]
And they were not used for that.

On 11/8/18 3:50 PM, Adrian Pope wrote:

Also, after the original post I realized that my estimates for 8-thread and 54-thread timings are overly optimistic due to power/clock-frequency effects. I ran a single phosim instance on a KNL node, so not load balanced. When there are only a few threads left running the bright objects, the active cores can use more power and increase the clock frequency more than if the node is loaded. I don't know the magnitude of this effect, but I expect it to be <2x from previous experiments. Anyway, the CPU time estimates for sourceLoop are going to be a bit low because of this, so the 8-thread and 54-thread projects for sourceLoop should be a bit higher. But, again, this test was not meant to be used for performance projection.

**Comment by fjaviersanchez** [comment]
@katrinheitmann, out of curiosity, I saw that the latest PhoSim version is 4.0.4 and that it includes things like complex galaxy morphologies (see more [here](https://bitbucket.org/phosim/phosim_release/wiki/Release%20Notes%20for%20v4.0.X)) Are we considering using it? According to the release notes PhoSim 4.0.1 and up seem to include some performance improvements for multi-threaded applications. Maybe (hopefully) switching to a newer version reduces the total computing time? However, switching versions would require some work to find what settings we should use for our runs so I guess it's risky. In any case, for the sake of testing I think that it would be interesting to see how this performs.

**Comment by katrinheitmann** [comment]
As you point out, it's somewhat risky, since we have done all our validation and testing with version 3.7.x. So we would need to do quite a bit more testing. We should discuss this in more detail.

On 11/8/18 5:28 PM, fjaviersanchez wrote:

@katrinheitmann<https://github.com/katrinheitmann>, out of curiosity, I saw that the latest PhoSim version is 4.0.4 and that it includes things like complex galaxy morphologies (see more here<https://bitbucket.org/phosim/phosim_release/wiki/Release%20Notes%20for%20v4.0.X>) Are we considering using it? According to the release notes PhoSim 4.0.1 and up seem to include some performance improvements for multi-threaded applications. Maybe (hopefully) switching to a newer version reduces the total computing time? However, switching versions would require some work to find what settings we should use for our runs so I guess it's risky. In any case, for the sake of testing I think that it would be interesting to see how this performs.

**Comment by katrinheitmann** [comment]
@adrianpope I think we can close this issue, right? Thanks!

**Comment by adrianpope** [comment]
Sure!
