### ISSUE TITLE
expected vs observed number density on Run1.2p

### ISSUE THREAD

**Issue by plaszczy** [LSSTDESC/DC2-production#306]
Following on a Rachel's proposal for (roughly) estimating the mean expected number of galaxies and comparing it to what is observed see:

https://github.com/LSSTDESC/DC2-production/blob/u/plaszczy/nb_run1_2/Notebooks/Number_density_Run1.2.ipynb

this is for Run1.2p but can obviously be used for other outputs.

So essentially where we wait for 2M , we measure 1M ( on Run1.2p). 
That's not bad (although it is here without extiction) and one should not expect any high precision (jusrt order of magnitude)

Note the bump on the mag_i histogram that is strange. 
feedback welcome.

**Comment by fjaviersanchez** [comment]
@plaszczy Thanks a lot for putting this together. About the number density, when you use the extendedness > 0.9 and the good==True cut, you may get rid of actual galaxies (especially on the fainter end). I don't expect the efficiency of these cuts to be as low as 50% but we haven't actually checked them for this sample yet. As you say, I think we are on the right order of magnitude, so this is good news.

About the bump in the magnitude histogram... I think this may be related with the color mismatch between protoDC2 and these catalogs (due to the way we matched the magnitudes from the catalog to the SEDs that we input to imSim and phoSim). In any case, to make sure, could you please add a plot showing the magnitude distribution for `dc2_reference_1.2` (you can load it using `GCRCatalogs`)?

**Comment by plaszczy** [comment]
@fjaviersanchez as Rachel pointed it a factor of 2 is already a very nice agreement.
concerning the extendedness cut I was surprized to see it is actually a binary value: 0 or 1. So I keep ones.
not using it would add maybe 30% of data, but not a factor of 2.

**Comment by katrinheitmann** [comment]
@plaszczy I think we can close this, right? Feel free to reopen if you have more questions.

**Comment by rmandelb** [comment]
For reference, I am putting a link to the latest on the Run 1.2p object vs. truth comparison here: https://github.com/LSSTDESC/DC2-analysis/pull/74 .  The bump that @plaszczy highlighted in the magnitude distribution in his notebook appears in the linked plots as well, in both the truth and object catalogs, which supports  @fjaviersanchez 's suggestion in this issue that it is related to the color mismatch between protoDC2 and the Run 1.2 image simulations.  The match in number densities appears to be very good!
