### ISSUE TITLE
Determine Run2.2i Processing Plan

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#369]
It sounds like we will process year by year, starting with y1-wfd or y6-wfd, so that the data for DR1 will be made available asap, see: https://github.com/LSSTDESC/DC2-production/issues/368#issuecomment-531053781
There are a few outstanding issues to sort out:

WFD
- [x] What years are we running:  y1-y5 or y6-y10? pending decision on sprinkling bright AGNs See #373 
- [x] What years will be run at which sites:  ALCF, NERSC, and Grid?

DDF
- [ ] Low fidelity sims, where?
- [ ] Check Low fidelity output
- [ ] Pending results of low fidelity sims, run high fidelity sims (where?)

**Comment by katrinheitmann** [comment]
Given that we might want to use Run 2.1i with AGNs later on for comparison, I think we should go with Y1-Y5. There will be no sprinkling of bright AGNs in Run 2.2i. NERSC time is running out again in January. So we should start there with Y1. 

DDF is still not ready.

**Comment by katrinheitmann** [comment]
After talking to Antonio, it seems that we can get 2 years out of Cori, one year from ALCF and the rest on the grid. So for now:

- Y1/Y2 on Cori
- Y3 on ALCF
-Y4/Y5 on grid.

**Comment by heather999** [comment]
and now we can update this with
Y4 on Cori
Y5 on grid

**Comment by katrinheitmann** [comment]
Since Run 2.2i image simulations have been concluded, this issue can be closed. We did not end up to do a full Run 3.0i at low fidelity but rather did smaller complete test runs and then started Run 3.0i on Theta. While validation still needs to be done on Run 3.0i, at least the processing plan has been worked out and if we have to rerun Run 3.0i, we should start a new issue.
