### ISSUE TITLE
Run metacal on dr1b to enable 3x2 validation test on Run 2.1i

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2-production#372]
The 3x2pt team measured xi_plus from metacal analysis of Run 2.1.1i (25 sq degree). The results are shown below (capture from their Slack channel #desc-3x2pt). This is a very important validation result for DC2. However, the area for Run 2.1.1.i is rather small and the scatter in the test still very large. Run2.1i dr1b would increase the area by > 10x with the same depth and should help to improve the test results. The AGN problem of Run 2.1i is not of much concern for this test, so this will be very informative if Run 2.2i will be ok on the shear-shear measurement front. It would be therefore important to carry out this validation test before Run 2.2i production. The main task is to rerun metacal in Run 2.1i.

![xip_plus_metacal](https://user-images.githubusercontent.com/12860812/65777792-4e3c2d80-e10a-11e9-80dc-da13489ff902.png)

**Comment by johannct** [comment]
this is running at CC : https://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/task.jsp?refreshRate=60&task=53661482&refreshIsOn=true&refreshCount=39
weekly 19, new pipeline in order to correctly run post patch merging into tracts (and to solve the https server modification to the XML schema). Only metacal (no  ngmix bd flux, which is very long to run)

**Comment by johannct** [comment]
Pipeline task is completed. Four tracts are missing : 
- 3454 : at coadd level only u and y meas/srcMatch/srcMatchFull files
- 2909, 2735,4428 : merging code rejected the 3+1+1 patches due to "No good isPrimary entries"

@airnandez  requesting transfer of `rerun/metacal-dr1b-v2` and `dpdd/coadd-dr1b-v1\:metacal-dr1b-v2/` under `/sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v2`

**Comment by joezuntz** [comment]
We now have 3x2pt measurements on 2.1i as well as 2.2.1i.

The lensing signal looks good!  I'm looking into the GGL and clustering signals, which I'm confused about because one of my outputs says there were zero lensing galaxies, but does return a signal, so I've clearly messed up somewhere.

xi_plus and xi_minus plots below



![xip_plus_metacal](https://user-images.githubusercontent.com/220537/66909859-66b2b000-f005-11e9-80ff-4a64fb1d8ef4.png)



![xip_minus_metacal](https://user-images.githubusercontent.com/220537/66912305-3f121680-f00a-11e9-8fe7-fa590324f1bf.png)

**Comment by rmandelb** [comment]
Nice!  The increased area has definitely made for less-ratty-looking signals.  Looking forward to GGL and clustering as well, once you've solved the mystery of the sample with zero galaxies...

**Comment by joezuntz** [comment]
I have the GGL and wtheta plots checked now - see below.

The signal is pretty small in the GGL plot, which I think gives rise to the apparently noisiness and presumably comes from the poor redshift selection, which is uncalibrated.  I can't check that hypothesis yet because we don't have a match to the input sample with the true redshifts.

![gamma](https://user-images.githubusercontent.com/220537/67019967-5e39a280-f0f5-11e9-89fd-9aaeb58b34f3.png)


![w](https://user-images.githubusercontent.com/220537/67019948-5679fe00-f0f5-11e9-960b-60883cc3625e.png)

**Comment by joezuntz** [comment]
Here's the estimated n(z), but that's completely uncalibrated and using a somewhat random trained model I had from earlier on:

![nz](https://user-images.githubusercontent.com/220537/67020445-25e69400-f0f6-11e9-97eb-dac5a1032afb.png)

**Comment by katrinheitmann** [comment]
@joezuntz Is there an update on this? Thanks a lot!

**Comment by joezuntz** [comment]
I have a possible repair for the issues I've seen but still have to debug the new version, so nothing concrete yet, sorry.

**Comment by katrinheitmann** [comment]
Hi @joezuntz, any further updates on this? Thanks!

**Comment by katrinheitmann** [comment]
Since we have by now retired Run 2.1i I am closing this issue which has been quiet for ~6 months. We should open a new one for Run 2.2i and metacal as needed. If you feel strongly about keeping it open, please reopen it. Thanks!
