### ISSUE TITLE
DC2 Planning Document

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2-production#39]
Since I took the liberty and renamed Phil's issue from DC2 Planning Document to DC2 Planning, I felt I should start a new one that deals with finishing the document. As Phil pointed out during the last mgmt meeting, it's time to finish up the plan and since we have almost completed the DC2 wish list spreadsheet, this is probably a good time to see where we are at. I list the different sections and their current states below. The read-only link is here: https://www.overleaf.com/read/jwbjvjnszkzf
If you are eager to edit and you don't have permission, please let me know.

- [x] 1 Introduction: short but sufficient I think. People should read it and add to it if they feel important information is missing. Ready for review.
- [x] 2 Planned uses: have input from all analysis working groups and technical working groups. Ready for review.
- [x] 3 DC2 Pipeline and Workflow: This is information about our data production process and a subsection on workflow engines. It sets the stage for the following sections. Ready for review.
- [x] 4 DC2 Extragalactic Catalog: This section describes the N-body simulation and data products, the catalog generation tools, and the catalog content. At the end of the section we have a short list of remaining tasks that have been so far identified working with the analysis working groups and CatSim. Ready for review.
- [x] 5 DC2 CatSim Catalog: This section gives a short description of CatSim's role, inputs, and outputs. Ready for review.
- [ ] 6 DC2 Image and DM Catalog: Mirroring Section 5, this section describes the tools and content of the catalogs. In particular Section 6.2 and 6.3 need work. NOT READY FOR REVIEW.
- [x] 7 Timeline: This section describes our 2 stage approach. After some more discussions this might be extended to more than 2 stages (with regard to area covered, bands simulated, and years of observations). It also might need more details on the imsim vs phosim usage, though I think this will become much clearer during the first stage so I would not be too specific at this point. With those caveats in mind, the section is ready for review.
- [ ] 8 Features and DM Feature set: this section has only a view bullet points and needs to be finished. Hopefully will be done when the DC2 wishlist is finalized. NOT READY FOR REVIEW.
- [ ] 9 Output Formats and Processing: Yao will add text to section 9.1 on the extragalactic catalogs. The rest of the section is currently blank. I think the Sprint week will be a good time to fill this in, but people should feel free to add to it already. NOT READY FOR REVIEW.
- [ ] 10 Validation Tests: This section describes our plan for validation and verifiction tests for both the extragalactic and image catalogs. We could think about breaking this section up and adding it sections 4 and 6. In this case, Section 10.1 is ready for review, section 10.2 needs to be written.
- [ ] 11 Computational Resources: This section describes our computing needs for both allocation and storage. While we do have all the information to fill this section in, we haven't had the time yet. NOT READY FOR REVIEW.

**Comment by rmandelb** [comment]
@katrinheitmann - I am not sure how you want comments to be sent (put directly in the document?  Should I just edit directly?).  For now, I am making some notes here.  I started looking at this with an eye towards making sure that the analysis WGs can see how this meets their needs.

In section 4.3, it says: "Redshift information: Cosmological redshift, observed redshift due to both the Hubble flow and the galaxy's proper motion, redshift due to proper motion."  I normally think of proper motion as referring to motion in the plane of the sky, which by definition cannot affect redshift, but here it twice mentions proper motion.  So the questions are (a) what does this mean and (b) why is it mentioned twice as if it's two separate things?  For (a), should it say "peculiar velocity" instead of "proper motion"?

Should "Abundance Stellar Metals" (which seems like unusual phrasing to me) be "Stellar metallicities"? (more common)

Later this week I will look at the spreadsheet and see what I can fill in.

**Comment by katrinheitmann** [comment]
@evevkovacs Hi Eve, you mentioned that you addressed Rachel's questions above, did you address all of them? Thanks!

**Comment by evevkovacs** [comment]
Yes, changed to using peculiar velocity instead of proper motion, deleted repeat mention and changed to using stellar metallicities.

**Comment by katrinheitmann** [comment]
Given that we are now writing the actual DC2 paper, I am closing it. I don't think we will ever fully finish the planning document.
