### ISSUE TITLE
Run2.2i DR6-WFD release

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/DC2-production#397]
This issue is to capture the discussion concerning preparation and validation of DR6 and its precursor releases such as DR6c, DR6d.

To Do 

- [x] Identify a consistent set of object and metacal catalogs and pixel level data for release
- [ ] Identify [validation criteria](https://lsstc.slack.com/archives/CM6MF33UG/p1597700298336400)
- [x] Fix any bad coadd files see https://github.com/LSSTDESC/ImageProcessingPipelines/issues/158
- [x] Update [desc-dc2-dm-data](https://github.com/LSSTDESC/desc-dc2-dm-data)
- [x] Create a new GCRCatalogs release that includes this data
- [x] Prepare and update documentation
- [x] Make an announcement

**Comment by erykoff** [comment]
As I promised on the Wednesday telecon, I have looked into the exposure time map to propose a region that should be the "DR6 WFD" footprint, avoiding the DDF fields which will only complicate analysis; these deep coadds can be in a separate catalog to make it clear that this is a fundamentally different dataset.

Here is what the i-band exptime map looks like as of the rsynced files the other day:

![image](https://user-images.githubusercontent.com/5167891/90796671-75709000-e2c4-11ea-9b34-5d56b306ac38.png)

The scale is cut at 4000 because otherwise we're looking at the upper right corner blowing everything out.  Zooming in, we get:
![image](https://user-images.githubusercontent.com/5167891/90796760-9507b880-e2c4-11ea-9be2-ce0b5bd8688c.png)

Note that tracts 4848, 4849, 5062, 5063, 5064 are not in the map since they are not done processing.  I propose first of all that we exclude those.

The tricker question is 4850.  Exclude the whole tract or just the dense patches?  (We have to be careful then).  These are the patches:

![image](https://user-images.githubusercontent.com/5167891/90796914-cb453800-e2c4-11ea-88a1-750247ce5c38.png)

If we exclude patches, I propose a "clean" cut excluding 4850: 4,3^5,3^6,3^4,4^5,4^6,4^4,5^5,5^6,5^4,6^5,6^6,6 .

Meanwhile, I noticed that two tract parquet catalogs that are nominally in the coverage are not on nersc.  These are 4428 and 2909.  These are at the hairy edge and could probably be excluded, but we want to do so explicitly:

![image](https://user-images.githubusercontent.com/5167891/90797291-4dcdf780-e2c5-11ea-99f9-552b65486e67.png)

![image](https://user-images.githubusercontent.com/5167891/90797333-5aeae680-e2c5-11ea-91dc-6be585cabdee.png)

This leaves the following "full" tracts in the proposed DR6 footprint, with the question of what to do with 4850:

```
2723^2724^2725^2726^2727^2728^2729^2730^2731^2732^2733^2734^2735^2896^2897^2898^2899^2900^2901^2902^2903^2904^2905^2906^2907^2908^3074^3075^3076^3077^3078^3079^3080^3081^3082^3083^3084^3085^3086^3256^3257^3258^3259^3260^3261^3262^3263^3264^3265^3266^3267^3268^3441^3442^3443^3444^3445^3446^3447^3448^3449^3450^3451^3452^3453^3454^3631^3632^3633^3634^3635^3636^3637^3638^3639^3640^3641^3642^3643^3825^3826^3827^3828^3829^3830^3831^3832^3833^3834^3835^3836^3837^4022^4023^4024^4025^4026^4027^4028^4029^4030^4031^4032^4033^4034^4035^4224^4225^4226^4227^4228^4229^4230^4231^4232^4233^4234^4235^4236^4429^4430^4431^4432^4433^4434^4435^4436^4437^4438^4439^4440^4441^4636^4637^4638^4639^4640^4641^4642^4643^4644^4645^4646^4647^4648^4851^4852^4853^4854^4855^4856^4857^4858^4859^4860^5065^5066^5067^5068^5069^5070^5071^5072^5073^5074
```

**Comment by erykoff** [comment]
Oh, and one could also argue that for 4850 we should exclude all the patches 4,* and 5,* and 6,*.

**Comment by wmwv** [comment]
> Meanwhile, I noticed that two tract parquet catalogs that are nominally in the coverage are not on nersc. These are 4428 and 2909. These are at the hairy edge and could probably be excluded, but we want to do so explicitly:

I agree.  We should definitely exclude 2909 and 4488.

**Comment by erykoff** [comment]
4428 not 4488, and yes, that is my proposal.

**Comment by wmwv** [comment]
> If we exclude patches, I propose a "clean" cut excluding 4850: 4,3^5,3^6,3^4,4^5,4^6,4^4,5^5,5^6,5^4,6^5,6^6,6 .

I agree.

**Comment by heather999** [comment]
I've made a copy of the pixel data directories within the same area `/global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/desc_dm_drp/v19.0.0-v1/rerun`, naming them `run2.2i-coadd-wfd-dr6d`, `run2.2i-coadd-wfd-dr6d-u`, `run2.2i-wfd-coadd-dr6d-grizy` and removed the suggested tracts and for tract 4850, those 12 patches. I've put copies of the `repositoryCfs.yaml` files onto CSCRATCH so we can continue to trick the butler and avoid issues if running in batch at NERSC. I think this is ready to go.

**Comment by heather999** [comment]
After discussing this at today's DESC DM meeting - I have done the following:
* Made sure that the full tracts we are excluding are not included in the object or metacal catalog areas for DR6d.
* For tract 4850: reran make_object_catalog, using the DR6d rerun area where those 12 patches in tract 4850 are excluded. Then merged the parquet files to produce the DR6d 4850 object catalog
```
python DC2-production-0.4.0/scripts/make_object_catalog.py /global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/desc_dm_drp/v19.0.0-v1/rerun/run2.2i-coadd-wfd-dr6d 4850 -o $PWD/output
python DC2-production-0.4.0/scripts/merge_parquet_files.py $PWD/output/object_4850_*.parquet -o $PWD/output/object_tract_4850.parquet --assume-consistent-schema
```
* Using the existing metacal tract/patch files for 4850, removing the files for those 12 patches, merged the resulting parquet files to produce a new 4850 metacal parquet file
```
python DC2-production-0.4.0/scripts/merge_parquet_files.py /global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/dpdd/run2.2i-wfd-dr6d/metacal_table_summary/4850/metacal_4850*.parquet -o /global/cfs/cdirs/lsst/production/DC2_ImSim/Run2.2i/dpdd/run2.2i-wfd-dr6d/metacal_table_summary/4850/metacal_tract_4850.parquet
```
The versions of the software used should be identical to what is in use at CC and is documented in the [IPP repo](https://github.com/LSSTDESC/ImageProcessingPipelines/blob/DC2-Run2.2i-1.2.0/workflows/srs/env_config/setup_desc_drp.sh). This includes LSSTDESC/DC2-production 0.4.0.

I'm going to copy these catalogs to the shared area at NERSC and start up a GitHub issue on GCRCatalogs to see about getting these included.

**Comment by heather999** [comment]
Naming discussion ongoing in https://github.com/LSSTDESC/gcr-catalogs/pull/483  Settling on dr6-wfd-v1, I've set aside the CC rsync rerun areas and renamed what were the dr6d rerun directories to:
```
run2.2i-coadd-wfd-dr6-v1
run2.2i-coadd-wfd-dr6-v1-u
run2.2i-coadd-wfd-dr6-v1-grizy
```

**Comment by yymao** [comment]
Sorry for coming late to the party but I feel this naming scheme is a bit confusing -- is `run2.2i-coadd-wfd-dr6-v1-u` a subset of `run2.2i-coadd-wfd-dr6-v1` or an independent data set?

**Comment by heather999** [comment]
Sorry, yes it is confusing 
run2.2i-coadd-wfd-dr6-v1 is the full datset composed of 2 subsets which are stored in two other directories  (run2.2i-coadd-wfd-dr6-v1-u and  run2.2i-coadd-wfd-dr6-v1-grizy) due to the need for different configuration parameters during the processing. Users would only need to be aware of run2.2i-coadd-wfd-dr6-v1. so we're really only talking about one dataset.

**Comment by yymao** [comment]
Thanks for the clarification. That's fine as long as it's documented. I still wonder if we should alias `run2.2i-coadd-wfd-dr6` to `run2.2i-coadd-wfd-dr6-v1` in GCRCatalogs

**Comment by wmwv** [comment]
@heather999 I've run `write_gcr_to_parquet.py` for `dc2_object_run2.2i_dr6_wfd_v1` using 

`DC2-production` commit `2882ade`
`gcr-catalogs` commit `c93c01b`  (the PR for issues/482, https://github.com/LSSTDESC/gcr-catalogs/pull/483)

And copied the results to

`/global/cfs/projectdirs/lsst/production/DC2_ImSim/Run2.2i/dpdd/run2.2i-wfd-dr6d/dc2_object_run2.2i_dr6d`

**Comment by wmwv** [comment]
RA, Dec Coverage looks correct

<img width="756" alt="DC2_Run2 2i_DR6d_ra_dec" src="https://user-images.githubusercontent.com/3201257/92523201-f947d900-f1ed-11ea-9a93-26a643122f49.png">

**Comment by heather999** [comment]
@wmwv Just catching up on this. I think I should copy the contents of `/global/cfs/projectdirs/lsst/production/DC2_ImSim/Run2.2i/dpdd/run2.2i-wfd-dr6d/dc2_object_run2.2i_dr6d` to `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/dpdd/Run2.2i-dr6-wfd-v1/dc2_object_run2.2i_dr6_wfd_v1` - just want to make sure.  Actually, I'll go ahead and do that - I can remove it if that's an error.

I'd like to target Monday morning to officially announce DR6 WFD. What pieces are we missing @JoanneBogart @yymao ?  I made a start at updating the [Confluence page](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+DRP+DC2+Run2.2i+Processing).  We probably should include a reference about the DPDD translation of the object catalogs on Confluence as well to help capture the [discussion on Slack](https://lsstc.slack.com/archives/CB30ND9CG/p1595517191247400)?

**Comment by yymao** [comment]
We can include a link to the translate [link here](https://github.com/LSSTDESC/gcr-catalogs/blob/v1.0.0/GCRCatalogs/dc2_object.py#L683) and make it clear that if one uses GCR or the "DPDD" parquet files (that Michael generated) then they are using the "translated" version. 

We should certainly avoid reproduce the translation code on confluence since we'll certainly forget to update it in the future.

**Comment by heather999** [comment]
We seem to be finished :)
