### ISSUE TITLE
Remember to add magnitudes in the final dataframe/catalog

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DC2-production#41]
This issue is just a reminder for whenever production is ready.

Right now in the dataframes that we produced for DC1 we forgot to include the magnitude (we include the fluxes but the zeropoints change so to convert to magnitude you have to query the zeropoints). I think it would be a good addition for DC2 to include also the magnitudes without having to get the zeropoints (since we are opening the FITS files with the butler already while generating the dataframes/catalogs it is just a little bit of more work to add the columns with the magnitudes).

**Comment by egawiser** [comment]
@fjaviersanchez sorry if I missed an earlier discussion, but what kind of fluxes and zeropoints are being used?  The standard are flux densities in microJy, and to convert those to AB magnitudes (and back) one only needs to use a fixed zeropoint of 23.9 magnitudes = 1 microJy.  What am I missing, and what can we do to stop the insanity of not using that system?

**Comment by fjaviersanchez** [comment]
The flux is expressed in terms of total counts so we need some reference (that changes patch to patch) to convert to AB. I have been doing this by reading the coadd calibrated exposures but I think we should include the magnitudes by default (because at the end of the day most people work in DESC will work with these)

**Comment by fjaviersanchez** [comment]
Just to clarify, I am talking about the output of the DM stack which we are propagating to pandas dataframes

**Comment by egawiser** [comment]
We should always propagate flux densities and uncertainties on them and let people convert to magnitudes at the end of the process.  This is critical because the actual uncertainties are much closer to symmetrical in flux density, and because objects can have negative or very small measured flux density which leads to trouble with magnitudes.  So we should be keeping object counts (if you need them for debugging purposes, but don't call them fluxes) along with flux densities (in microJy) and uncertainties on the latter.

**Comment by cwwalter** [comment]
Eric, just to clarify; are you saying that we should always make sure we keep the information that allow people to calculate the magnitudes, or that we also shouldn't ever include the nominal calculated magnitudes in the final data frame we distribute?  I think this is equivalent to the ugriz magnitudes returned by the SDSS sky server right?

That is what we are talking about here.  If you need to calculate them every time yourself you need to run a process to add them to the data frame for later commands and it's nice to already have it there.

**Comment by egawiser** [comment]
What I'm saying is that as long as you keep the flux densities in microJansky (for each band), everyone can calculate magnitudes using the formula mag_AB = 23.9 - 2.5 log_10 (flux density).  Flux uncertainties can similarly be turned into magnitude uncertainties.  It's fine to also include the calculated magnitudes, if you're feeling generous on the storage side, but they are redundant information.  It's not symmetrical i.e. you can't keep magnitudes and simply turn them into flux densities, because negative flux densities usually get turned into magnitude flags (I'm not sure what the DM Stack does, but the formula for reversing it is either non-existent or non-obvious).

**Comment by cwwalter** [comment]
OK, yes, I agree about keeping the raw information. I think for practical reasons it is also good to give people the magnitudes if they want to use them.  There are base_PsfFlux_flux and modelfit_CModel_flux returned by the stack. We are using a zero point that I think was calculated by @danielsf with our throughputs and I'm not positive about all of the units used off the top of my head.

**Comment by egawiser** [comment]
Right, but anything that requires you to calculate a zeropoint must be in "raw" counts.  My point is that you should (also) report those as flux densities and uncertainties in microJansky.  At that point there are no more zeropoints to worry about, and anyone can make the further conversion of those into magnitudes and magnitude uncertainties if it takes too much space to keep everything.  Not offering flux densities and uncertainties in microJansky is unacceptable.

**Comment by cwwalter** [comment]
OK. Javier, can you also add a separate issue about reporting each flux and uncertainty in microJanskys in addition to the stack fluxes? Thanks.

**Comment by fjaviersanchez** [comment]
Ok, I am opening another issue. Just for completeness, the stack reports a zeropoint (in ADUs) that allows you to convert to AB magnitudes (and/or flux density), this zeropoint is computed for each calibrated exposure. We should think about what is the most efficient way to store/distribute this.

**Comment by danielsf** [comment]
The official LSST rule as handed down by (I assume) the PST is that we define flux (densities) in Janskys, so the zeropoint is `2.5*log10(3631) = 8.9`

https://github.com/lsst/sims_photUtils/blob/master/python/lsst/sims/photUtils/Sed.py#L403

**Comment by fjaviersanchez** [comment]
I think we can close this since the catalogs already include magnitudes (and or fluxes in nJy)
