### ISSUE TITLE
Implement extra rotational dithering into OpSim

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2-production#6]
The afterburner scheme we have now as implemented by @rhiannonlynne , @SimonKrughoff , @humnaawan, @egawiser  etc works well and makes a random rotational dither after each filter change.

However, as these rotations are done after the scheduler has run, some may be unphysical due to the constraint of the physical lengths of the cable restricting how far the camera can actually move.

To be properly implemented this would actually need to be implemented in OpSim.

Should we actually do this, if so when?

**Comment by humnaawan** [comment]
@cwwalter perhaps @rhiannonlynne @SimonKrughoff can say more but as I understand, the rotator resets to its starting position after every filter change, and since we aren't implementing very large rotational dithers all the time (occasionally there's a 90deg dither though), the physicality shouldn't be a big problem. I think the idea of some sort of cost function came up during the last AAS meeting but I'm unsure if something like it exists right now.

If we have the machinery set up to run OpSim simulation on our own, we can presumably run different cadences and optimize the rotational dithers.

**Comment by SimonKrughoff** [comment]
I'm not sure I'm the right person to comment on this.  I don't know what systematics we could introduce by being a little non-physical.  Naïvely, it seems like it should be fine to just use the same afterburner scheme even though it's not completely correct.

**Comment by egawiser** [comment]
I don't think the minor differences between the rotational dithering scheme that we used for DC1 are a concern for DC2, so I suggest that we keep using it.  There is an issue with cable wrapping and the range of allowed instrument rotations that prevents our randomly chosen rotation angle from always being realizable, but in practice a smarter-than-random choice of rotator angle could make things turn out almost identically to what we're simulating by the end of 1-10 years.

**Comment by cwwalter** [comment]
OK, let's stick with this for DC2.

This should be on our list for DC3.  I am going to leave this open for a bit as a reminder.  I will setup up a DC3 repo later and make a issue there.

**Comment by katrinheitmann** [comment]
We have moved this question into DC3 planning as suggested above. The DC3 planning github issue is linked here: LSSTDESC/DC3-planning#1
