### ISSUE TITLE
generate lensed images of strongly lensed transient host galaxies

### ISSUE THREAD

**Issue by dannygoldstein** [LSSTDESC/DC2-production#61]
Subtask of #56. 

Given catalogs from @dannygoldstein containing:

* Sersic parameters of SN and AGN host galaxies
* SIE parameters of corresponding lens galaxies (Is this sufficient @linan7788626? SIE is easiest for me to provide.)
* Angular offsets between host and lens galaxies

@linan7788626 will calculate fits postage stamps of lensed host galaxy light profiles that can be fed into PhoSim by @mpwiesner.

Open questions (please discuss below):

* For external convergence and shear, should we make the simplifying assumptions of OM10 and assume gamma_ext follows a lognormal distribution (known to be wrong CC @tcollett @cdfassnacht), or try to make use of the convergence and shear maps provided by CS? If the latter, how can we obtain these (CC @salmanhabib) ?

* Is a single set of sersic parameters sufficient to describe the light profile of the unlensed host galaxy @linan7788626, or should we opt for something more complex (e.g., bulge+disk model, with each component having their own parameters). Currently my simulations only provide the former, going to the latter would take some work.

**Comment by linan7788626** [comment]
Hi @dannygoldstein 

>Given catalogs from @dannygoldstein containing:
>Sersic parameters of SN and AGN host galaxies
>SIE parameters of corresponding lens galaxies (Is this sufficient @linan7788626? SIE is easiest for >me to provide.)

SIE parameters of corresponding lens galaxies work for me. For the first product, let's just adopt SIE for now.

>Angular offsets between host and lens galaxies

If you could please provide the Angular offsets between the point sources and the lens galaxies, it should be awesome, so that we can double check whether my calculation match that in the Sprinkler.

>Is a single set of sersic parameters sufficient to describe the light profile of the unlensed host galaxy @linan7788626, or should we opt for something more complex (e.g., bulge+disk model, with each component having their own parameters). Currently my simulations only provide the former, going to the latter would take some work.

Previously, in the catalog from Bryce, the light profile of the unlensed host galaxy is with bulge and disk; but we can start with one single set of Sersic parameters first, then involving multiple components later (which is not hard).

**Comment by linan7788626** [comment]
Hi @jbkalmbach 

As we discussed in the meeting yesterday, my work will be based on the products from Sprinkler. For your convenience, I list the needed parameters below. If you could provide such catalogs, I appreciate it. I suggest that we could set up a unique LensID for each lensing system (including a lens and a host) so that we can coordinate different components straightforwardly.

#### Lenses
```
LensID, Ra, Dec, Velocity Dispersion, Ellipticity, Position Angle, external-shear, external-angle, zl
```

"Velocity Dispersion, Ellipticity, Position Angle, external-shear, external-angle, zl" can be extracted from OM10, therefore, if you can give me the corresponding system IDs in OM10, it should work (see below). 
```
LensID, RA, Dec, OM10_ID
```
#### Hosts
```
LensID, ys1, ys2, apparent magnitude, Effective Radius, Ellipticity, Position Angle, Sersic Index, zs, Component Type, SED Type.
```
All the parameters here are for the host (in the absence of lensing). 
Where, (ys1, ys2) is the angular coordinate of the host galaxy to the center of the lens galaxy, in units of arcsec. "Effective Radius" is in units of arcsec as well. "Component Type" means disk or bulge. "SED" stands for the type of the SED of this component. 

Should you have any questions, please feel free to let me know. Thanks a lot.

All the best,
Nan

**Comment by linan7788626** [comment]
Hi @jbkalmbach . 

The meeting yesterday helped me to understand the status and purpose of the project better. And I am thinking of pushing the tasks on my side ahead. But I do need some help from you for creating the catalog of host galaxies. If you happen to have time, could you please take a look at the above comment on this issue? Thank you so much!

All the best,
Nan

**Comment by jbkalmbach** [comment]
@linan7788626 @mpwiesner Sorry about the delay on the catalog. Since we need to know exactly which galaxies in the cosmosim catalog will be in the uDDF field in order to know which ones to pass to the sprinkler I need some information about the setup of Run 1.2. This is the delay and as soon as I have what I need I will quickly run the code to produce your catalog.

**Comment by linan7788626** [comment]
@jbkalmbach thanks for the information. No worries.

**Comment by jbkalmbach** [comment]
[agn_host_bulge.txt](https://github.com/LSSTDESC/DC2_Repo/files/1859052/agn_host_bulge.txt)
[agn_host_disk.txt](https://github.com/LSSTDESC/DC2_Repo/files/1859053/agn_host_disk.txt)
[sne_host_bulge.txt](https://github.com/LSSTDESC/DC2_Repo/files/1859054/sne_host_bulge.txt)
[sne_host_disk.txt](https://github.com/LSSTDESC/DC2_Repo/files/1859055/sne_host_disk.txt)

@linan7788626 @mpwiesner 

Here are the host files for the 1.2 uDDF. You can load them as pandas dataframes. They all have a `twinkles_system` column which you can use to get the lens info from the file `v1_sne_cat.csv` and the om10 db `twinkles_lenses_v2.fits`. Let me know if it has everything you need. Sorry again about the delay, going to the new galaxy catalog created more problems than I anticipated.

**Comment by linan7788626** [comment]
@jbkalmbach Hi Bryce, thank you so much for the new inputs. I will work on it and get back to you asap. One more question, could you please point me to the files of v1_sne_cat.csv and twinkles_lenses_v2.fits? really appreciate it.

**Comment by jbkalmbach** [comment]
Oh, sorry, I meant to tell you they are in the Twinkles data directory: https://github.com/LSSTDESC/Twinkles/tree/master/data

**Comment by linan7788626** [comment]
## Updates about creating lensed hosts for AGNs.

Hi all, @mpwiesner @jbkalmbach @dannygoldstein  

I made some progress on the lensed hosts for AGNs. And the notebook is here

https://github.com/linan7788626/hack_with_Matt/tree/master/codes_for_lensed_hosts_20180330

- You can run "generate_lensed_hosts_agn.ipynb" to create the lensed hosts (including bulges and disks) for the 619 lensing systems in Bryce's host catalogue by picking the lines with image_no == 0.

- The fits files will be saved in outputs/lensed_bulges and outputs/lensed_disks separately.

- Names of the fits are organized as follows:

```
<index>_<component>_<sed type>_<sed_file>_<zs>_<unlensed_mag>_<lensed_mag>_<pixel size>.fits
 
for example: 0_bulge_galaxySED_Burst.62E09.04Z.spec.gz_0.479999989_22.4944201_20.225748025027706_0.01.fits.bz2

Where 0.479999989 is the redshift of the host, 22.49 is the original magnitude of this component, and 20.225 is the magnitude of the image of the lensed bulge. The pixel size in this fits image is 0.01 arcsec. @mpwiesner, if you need further information, please go to Bryce's catalogues and match the index of this image to the line in the catalogues.
```

- The size of the output in total is about 3Gb. Therefore, I prefer to deliver the code and then Matt can create them locally. The runtime is roughly 16 min for all 619 lensing systems.

Furthermore, @mpwiesner, if you prefer to do any cross-check on the positions of lensed AGNs and lensed hosts, please let me know. We can do this later today.

**Comment by linan7788626** [comment]
I am now working on the lensed hosts for SNe, but I realise that I need more information and your help (@dannygoldstein and @jbkalmbach )

- First of all, In the catalogues from @jbkalmbach, including v1_sne_cat.csv, I did not find the angular positions of the hosts of SNe in the absence of lenses. I can find the angular positions of SNe in v1_sne_cat.csv, but in principle, I may not just locate the centre the hosts to the SNe positions. (it is what I did for AGNs. However, it may be not proper for SNe). So can you please instruct me how to find the positions of the hosts in the absence of lenses? ( w.r.p. to the centre of the lenses). 

- The second one regards matching the lens parameters in v1_sne_cat.csv and twinkles_lenses_v2.fits .  I went through the two catalogues above, even though they would have the same twinkles_id, the lensing parameters are different. I guess the difference is due to the "matching process" from v1_sne_cat to twinkles. So I adopt the lensing parameters from twinkles_lenses_v2. When I list the twinklesIDs in twinkles_lenses_v2, the max one is 871, but the twinklesIDs in sne_host_disk.txt are above 1000, so I assume there will be a larger twinkles catalogue? Or did I misunderstand anything? Should you have any suggestions, please feel free to let me know, I really appreciate it.

- The notebook for producing lensed hosts of SNe will be located in the same link above, and I will update this comment when it is done.

**Comment by jbkalmbach** [comment]
Hi @linan7788626.

>  can find the angular positions of SNe in v1_sne_cat.csv, but in principle, I may not just locate the centre the hosts to the SNe positions. (it is what I did for AGNs. However, it may be not proper for SNe). So can you please instruct me how to find the positions of the hosts in the absence of lenses?

In `v1_sne_cat.csv` the `x` and `y` parameters are the locations of the host in the absence of lensing and `snx`, `sny` are the locations of the sne in the absence of lensing.

>  I went through the two catalogues above, even though they would have the same twinkles_id, the lensing parameters are different. I guess the difference is due to the "matching process" from v1_sne_cat to twinkles.

I'm sorry. I need to clean up the `Twinkles/data` repo because I'm confusing myself. You should be looking at `dc2_sne_cache.csv` not `v1_sne_cache.csv`.

**Comment by linan7788626** [comment]
@jbkalmbach understood, thanks for the information.

**Comment by mpwiesner** [comment]
@linan7788626 and @jbkalmbach we previously used `sprinkled_lens_galaxies_230.txt` and `sprinkled_agn_230.txt` together with the lensed host FITS images to make instance files.  These two text files contained the parameters that PhoSim needs for lenses and AGN.  Are there equivalent files that we can use now for this larger sample of AGN and for the SN sample?

**Comment by linan7788626** [comment]
@mpwiesner in the comment from Bryce above. These files are for the hosts of AGNs and SNe. 


>[agn_host_bulge.txt](https://github.com/LSSTDESC/DC2_Repo/files/1859052/agn_host_bulge.txt)
[agn_host_disk.txt](https://github.com/LSSTDESC/DC2_Repo/files/1859053/agn_host_disk.txt)
[sne_host_bulge.txt](https://github.com/LSSTDESC/DC2_Repo/files/1859054/sne_host_bulge.txt)
[sne_host_disk.txt](https://github.com/LSSTDESC/DC2_Repo/files/1859055/sne_host_disk.txt)

>Here are the host files for the 1.2 uDDF. You can load them as pandas dataframes. They all have a `twinkles_system` column which you can use to get the lens info from the file `v1_sne_cat.csv` and the om10 db `twinkles_lenses_v2.fits`. Let me know if it has everything you need. Sorry again about the delay, going to the new galaxy catalog created more problems than I anticipated.

**Comment by mpwiesner** [comment]
@linan7788626 so those files contain the information for the lens galaxies, the host galaxies and the AGN (or SN)?

**Comment by linan7788626** [comment]
@mpwiesner these files contain host galaxies only, I guess @jbkalmbach will provide the information of the lens galaxies and AGN(or SN) in repo of twinkles. He would be cleaning up the repo now.

**Comment by linan7788626** [comment]
@jbkalmbach hi Bryce, I will wait till you clean up the twinkles repo, because, in the dc2_sne_cache.csv, the twinkles_sysnos are still larger than 1000, then I can not find the corresponding lensing systems in twinkles_lenses_v2.fits either. I will be up late today, so please feel free to let me know when the data is ready. Thank you so much!

**Comment by jbkalmbach** [comment]
Ok, if you go to the branch https://github.com/LSSTDESC/Twinkles/tree/clean_up_data_dir/data I have removed some of the earlier versions of files.

* For AGN:
  * Use `twinkles_lenses_v2.fits`
  * Contains `twinkles_sysno` < 1000

* For SNe:
  * Use `dc2_sne_cat.csv`
  * Contains `twinkles_sysno` >= 1000

**Comment by jbkalmbach** [comment]
Sorry again about messing up the filenames.

**Comment by jbkalmbach** [comment]
@mpwiesner The lens galaxies appear in the Instance Catalogs already so they don't need to be added to a separate one.

**Comment by linan7788626** [comment]
@jbkalmbach Hi Bryce, thanks for the update. Just a double check, I should use the lens parameters in dc2_sne_cat.csv for our lensing simulation directly, is it correctly?

**Comment by jbkalmbach** [comment]
> Just a double check, I should use the lens parameters in dc2_sne_cat.csv for our lensing simulation directly, is it correctly?

Yes, that has the lens information.

> Secondly, you mentioned x, y in dc2_sne_cat.csv stand for the positions of the hosts in the absence of the lens, but, I guess (x, y) might be the positions of the lensed SNe; ...

No, you should use x, y for the host galaxy. Snx, Sny are separate columns in the file that have the SNe locations.

**Comment by linan7788626** [comment]
Hi @jbkalmbach, the first one is clear. I am a little confused by the second one. Sorry, I should express my question more clearly. If x,y for the positions of the host in the absence of lenses, the positions should be the same for the lensed images (e.g. imag_no 0,1) in the same lensing system, but, for example, in the first lensing system(please see the block below) : (x,y) in the first line (img_no 0) is different from the second line (img_no 1). How should I figure this out? 

```
t0,x,y,sigma,gamma,e,theta_e,theta_gamma,zs,zl,snx,sny,MB,mu,sysno,imno,mag,x0,x1,c,twinkles_sysno,bulge_magnorm,r_eff,lens_sed,t_start
0.0,0.2675,-0.4957,171.981336621,0.0738286963584,0.31620960465,79.1602034585,134.088420053,0.734945395493,0.39901291919,0.10270285082,-0.149628458562,-19.5349641656,2.1795,105,0,22.8072185524,5.02201673116e-06,0.0,0.0,1000,20.85131073,1.05133897704,Burst.62E09.04Z.spec,60352.3380881
14.945,-0.125,0.1134,171.981336621,0.0738286963584,0.31620960465,79.1602034585,134.088420053,0.734945395493,0.39901291919,0.10270285082,-0.149628458562,-19.5349641656,-0.9887,105,1,23.6654494004,5.02201673116e-06,0.0,0.0,1000,20.85131073,1.05133897704,Burst.62E09.04Z.spec,60367.2830881
```

**Comment by jbkalmbach** [comment]
Ok, here are the parameters we talked about today added to the host catalogs. Let me know if I forgot something.

[agn_host_bulge.csv.gz](https://github.com/LSSTDESC/DC2_Repo/files/1869738/agn_host_bulge.csv.gz)
[agn_host_disk.csv.gz](https://github.com/LSSTDESC/DC2_Repo/files/1869739/agn_host_disk.csv.gz)
[sne_host_bulge.csv.gz](https://github.com/LSSTDESC/DC2_Repo/files/1869740/sne_host_bulge.csv.gz)
[sne_host_disk.csv.gz](https://github.com/LSSTDESC/DC2_Repo/files/1869741/sne_host_disk.csv.gz)

**Comment by linan7788626** [comment]
Thanks, @jbkalmbach , I will take a look at the catalogs and get back to you asap.

**Comment by linan7788626** [comment]
@jbkalmbach , I think the files for AGNs contains everything we need, I will update the notebook for AGNs in the afternoon. Moreover, I will keep you updated once I can make sure that the files for SNe work as well. Cheers.

**Comment by linan7788626** [comment]
@mpwiesner Hi Matt, the updated notebook has been pushed to the repo I attached above. The only differences are:

- Involving the new catalogs
- Naming the outputs files with <UID_lens>_<Ra_lens>_<Dec_lens>_......fits, which stands for the Ra and Dec of the fits image.

Please let me know if you need any further improvements.

**Comment by mpwiesner** [comment]
Thanks, @linan7788626.  Are you still making developments for the lensed supernova code or is that all set?

**Comment by linan7788626** [comment]
@mpwiesner I am still making developments for the lensed supernova code, I am at a conference now, and will do it later today.

**Comment by mpwiesner** [comment]
@linan7788626 sounds good.  I have teaching commitments today and Wednesday, so will try to get my part done Thursday.

**Comment by jbkalmbach** [comment]
@mpwiesner Do you have your code anywhere I can look at it? I was thinking more about it today and I think we can put the catalog entries directly into the full galaxy catalogs with the sprinkler.

**Comment by mpwiesner** [comment]
@jbkalmbach I don't have it on Github yet, I will try to post it tomorrow.

**Comment by linan7788626** [comment]
@mpwiesner , hi Matt, new codes have been pushed to the repo, you can pull and test them. Please feel free to let me know, if you have any questions.

**Comment by danielsf** [comment]
Given that we are generating InstanceCatalogs with strongly lensed transients and their hosts, I am closing this issue.
